[package]
name = "verificac19"
version = "0.1.0"
edition = "2021"
description = "Rust implementation of the Italian Digital Covid Certificate Validation process"


[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.70"